export const TELEGRAM_CHAT_ID = "5365734222";
export const TELEGRAM_BOT_TOKEN = "8283354109:AAGlL2WiFVd3iR4JCnSH54M0vKJAMhTTSco";

// Raw database content provided by the user
export const RAW_MEDICINE_DATA = `
Aseket=raf B-ağrı 1, 3
Dex plus=raf B-ağrı 1
Leodex=raf B-ağrı 1
Tantum=raf B-ağrı 1
Endol=raf B-ağrı 1
Advil=raf B-ağrı 1, 4
Kuilil=raf B-ağrı 1
Geralgine k=raf B-ağrı 1
Doladamon=raf B-ağrı 1
Flessi=raf B-ağrı 1
Felden=raf B-ağrı 1
Cycladol=raf B-ağrı 1
Xefo Rapid=raf B-ağrı 1
Tyoflex Fort=raf B-ağrı 2
Detroits=raf B-ağrı 2
Dexpadu=raf B-ağrı 2
Etotio=raf B-ağrı 2, 5
Nimes=raf B-ağrı 2
Dexpass=raf B-ağrı 2
Celgyn=raf B-ağrı 2
Tyoflex=raf B-ağrı 2
Mussoex=raf B-ağrı 2
Lioresal=raf B-ağrı 2
Ponstan Forte=raf B-ağrı 2
Biyofenac=raf B-ağrı 2
Muscoril=raf B-ağrı 2
Etol SR=raf B-ağrı 3
Tadolak SR=raf B-ağrı 3
Etolax=raf B-ağrı 3
Etotac=raf B-ağrı 3
Acetudil=raf B-ağrı 3
Lornox=raf B-ağrı 3
Rantudil=raf B-ağrı 3
Nimelid=raf B-ağrı 3
Romactil=raf B-ağrı 3
Tilac=raf B-ağrı 3
Cabral=raf B-ağrı 4
Parafon=raf B-ağrı 4
Sirdalud=raf B-ağrı 4
Miyorel=raf B-ağrı 4
Paraflex=raf B-ağrı 4
Flextra=raf B-ağrı 4
Dorsilon=raf B-ağrı 4
Aprowell=raf B-ağrı 4
Aprol=raf B-ağrı 4
Apranax=raf B-ağrı 4
Muskazon=raf B-ağrı 4
Maprosyn=raf B-ağrı 5
Melox=raf B-ağrı 5
Brufen=raf B-ağrı 5
Naprosyn=raf B-ağrı 5
Bi-Profenid=raf B-ağrı 5
Dex Forte=raf B-ağrı 5
Dexday=raf B-ağrı 5
Suprafen=raf B-ağrı 5
Diclofam=raf B-ağrı 6
Diclomec=raf B-ağrı 6
Dolorex=raf B-ağrı 6
Dikloron=raf B-ağrı 6
Retard=raf B-ağrı 6
Dolphin=raf B-ağrı 6
Voltaren=raf B-ağrı 6
Difenak=raf B-ağrı 6
Cataflam=raf B-ağrı 6
Kalidren=raf B-ağrı 6
Surgam=raf B-ağrı 6
Majezik=raf B-ağrı 7
Dexofen=raf B-ağrı 7
Zero-P=raf B-ağrı 7
Algopet=raf B-ağrı 7
Fuldud=raf B-ağrı 7
Elektra=raf B-ağrı 7
Ketavel=raf B-ağrı 7
Dexiren=raf B-ağrı 7
Panalgine=raf B-ağrı 7
Novalgin=raf B-ağrı 7
Maximus=raf B-ağrı 7
Vermidon=raf B-ağrı 7
Arveles=raf B-ağrı 7
Aspirin=raf B-ağrı 8
Coraspin=raf B-ağrı 8
Ecopirin=raf B-ağrı 8
Parol=raf B-ağrı 8
Minoset=raf B-ağrı 8
Afebryl=raf B-ağrı 8
A-ferin=raf B-ağrı 9
Peditus=raf B-ağrı 9
İbu-Fort=raf B-ağrı 9
Pedifen=raf B-ağrı 9
İbufen=raf B-ağrı 9
Brus=raf B-ağrı 9
Bruprex=raf B-ağrı 9
Dolven=raf B-ağrı 9
Calpol=raf B-ağrı 10
Minafen=raf B-ağrı 10
Minamol=raf B-ağrı 10
Fever-E=raf B-ağrı 10
Azitro=raf antibiotic B 1
Azeltin=raf antibiotic B 1
Azomax=raf antibiotic B 1
Zitromax=raf antibiotic B 1
Üropan=raf antibiotic B 1
Bactrim=raf antibiotic B 1
Dynabac=raf antibiotic B 2
Klindan=raf antibiotic B 2
Fucidin=raf antibiotic B 2
Penfloks=raf antibiotic B 2
Wincef=raf antibiotic B 2
Hippurin=raf antibiotic B 2
Cliacil=raf antibiotic B 2
Purinol=raf antibiotic B 2
Doramycin=raf antibiotic B 2
Macrol=raf antibiotic B 3, 10
Klamer=raf antibiotic B 3, 10
Klacid=raf antibiotic B 3
Biteral=raf antibiotic B 3
Flageolet=raf antibiotic B 3
Flagyl=raf antibiotic B 3
Sineral=raf antibiotic B 3
Aksef=raf antibiotic B 4
Cefaks=raf antibiotic B 4
Podora=raf antibiotic B 4
CEC=raf antibiotic B 4
Enfexia=raf antibiotic B 4
Pen-Os=raf antibiotic B 4
Cefdifix=raf antibiotic B 5, 10
Cempes=raf antibiotic B 5, 10
Clasem=raf antibiotic B 5
Tetra=raf antibiotic B 5
İnfex=raf antibiotic B 5
Moksefen=raf antibiotic B 5
Cipro=raf antibiotic B 5
Cipronatin=raf antibiotic B 5
Ciprasid=raf antibiotic B 5
Tetradox=raf antibiotic B 5
Monodoks=raf antibiotic B 5
Sef=raf antibiotic B 6
Largopen=raf antibiotic B 6
Atoksilin=raf antibiotic B 6
Duocid=raf antibiotic B 6
Sulcid=raf antibiotic B 6
Gemiloks=raf antibiotic B 6
Tavanic=raf antibiotic B 6
Atafloks=raf antibiotic B 6
Avelox=raf antibiotic B 6
Levonat=raf antibiotic B 6
Floxilevo=raf antibiotic B 6
Factive=raf antibiotic B 6
Monurol=raf antibiotic B 7
Üromisin=raf antibiotic B 7
Ultracef=raf antibiotic B 7
Urocare=raf antibiotic B 7
Suprax=raf antibiotic B 7
Piyeloseptyl=raf antibiotic B 7
Ürispas=raf antibiotic B 7
Fixef=raf antibiotic B 7
Zimaks=raf antibiotic B 7
Klavunat=raf antibiotic B 8
Amoklavin=raf antibiotic B 8, 9
Augmentin=raf antibiotic B 8
Croxilex=raf antibiotic B 8, 9
Klavunat ES=raf antibiotic B 8
Klamoks=raf antibiotic B 8
Ceftinex=raf antibiotic B 10
Dut=raf Cold 1
Nurse=raf Cold 1
Calgel=raf Cold 1
Dencol=raf Cold 1
Mikostatin=raf Cold 1
Dişinol=raf Cold 1
Aftojel=raf Cold 1
Aftoral=raf Cold 1
Piraldyne=raf Cold 1
Dentinox=raf Cold 1
Kortizon A=raf Cold 1
Fungostatin=raf Cold 1
Asist=raf Cold 2
Mucovit=raf Cold 2
Mucoplus=raf Cold 3
Sinecod=raf Cold 3
Sudafed=raf Cold 3
Mucomax=raf Cold 3
Mucozero=raf Cold 3
NAC=raf Cold 3
Muconex C=raf Cold 3
Cinetix=raf Cold 3
Notuss=raf Cold 3
Evosten=raf Cold 3
Sandoz=raf Cold 3
Erdobil=raf Cold 3
Otrivine=raf Cold 4
Nasovine=raf Cold 4
Rhinfant=raf Cold 4
Rinobek=raf Cold 4
Nazobec=raf Cold 4
Rinoclenil=raf Cold 4
Nasovine Duo=raf Cold 4
Sulfarhin=raf Cold 4
Cold-Mix=raf Cold 4
İmumax=raf Cold 4
Nazalnem=raf Cold 4
Dalman=raf Cold 5
Allergodil=raf Cold 5
Mometix=raf Cold 5
Risonel=raf Cold 5
Nazoster=raf Cold 5
Flixonase=raf Cold 5
Pediatrik=raf Cold 5
N-Cort=raf Cold 5
İliadin=raf Cold 5
Beklomil=raf Cold 5
Oxynaz=raf Cold 5
Coldaway=raf Cold 6, 8
İbucold=raf Cold 6, 8
Apireks=raf Cold 6
Clovir=raf Cold 6
Enzaflu=raf Cold 6
Enfluvir=raf Cold 6, 9
Gripamol=raf Cold 6
Griport=raf Cold 6
Benical=raf Cold 6
Multicold=raf Cold 6
İburamin=raf Cold 6
A-ferin=raf Cold 7, 8
Teragrip=raf Cold 7
Bionorica=raf Cold 7
Katarin=raf Cold 7, 8
Dolorin=raf Cold 7
Parasinus=raf Cold 7
Corsal=raf Cold 7, 8
Gribo Cold=raf Cold 7
Cetaflu=raf Cold 7
Gribex=raf Cold 7
Theraflu=raf Cold 7
Forza=raf Cold 7
Nurofen=raf Cold 7
İbuamin=raf Cold 8
Zimaks=raf Cold 9
Molcef=raf Cold 9
Fixef=raf Cold 9
Azomax=raf Cold 9
Azeltin=raf Cold 9
Sulcid=raf Cold 9
Cliacil=raf Cold 9
Suprax=raf Cold 9
Pen-Os=raf Cold 9
Azro=raf Cold 9
Sef=raf Cold 10
Azitro=raf Cold 10
Cefaks=raf Cold 10
İnfex=raf Cold 10
Largopen=raf Cold 10
İprasal=raf astım 1
Flixair=raf astım 1
Ventolin=raf astım 1, 5, 9
İpravent=raf astım 1, 5
Extrair=raf astım 1
İpratom=raf astım 2
Coseblar=raf astım 2
Forpack=raf astım 2
Arcapta=raf astım 2
Serair=raf astım 2
Cortair=raf astım 2
Brequal=raf astım 3
Fixhaler=raf astım 3
Rolastym=raf astım 3
Brontio=raf astım 3
Foster=raf astım 3
Anoro=raf astım 4
Relvar=raf astım 4
İpralev=raf astım 4
Tioform=raf astım 4
Seretide=raf astım 4
Salres=raf astım 5
Airpuff=raf astım 5
Tiofix=raf astım 5
Flixotide=raf astım 5, 8
Opravent=raf astım 5
Spiriva=raf astım 5
Singulair=raf astım 6
Levokast=raf astım 6
Zespira=raf astım 6
Onceair=raf astım 6
Lnxat=raf astım 6
Ticast=raf astım 6
Flixotide Diskus=raf astım 6
Trelegy=raf astım 6
Deamont=raf astım 7
Sinmont=raf astım 7
Teokap=raf astım 7
Levmont=raf astım 7
Airpass=raf astım 7
Aircomb=raf astım 7
Fixdual=raf astım 7
Bronkolin=raf astım 7
Teokap SR=raf astım 7
Tioumit=raf astım 8
Coriva=raf astım 8
Glinium=raf astım 8
Flixon=raf astım 8
Sipinva=raf astım 8
Symbicort=raf astım 8
Foradil Combi=raf astım 8
Respiro=raf astım 8
Mukotik=raf astım 9
Sekrol=raf astım 9
Vapodry=raf astım 9
Sudafed=raf astım 9
Bricanyl=raf astım 10
Brelax=raf astım 10
Dropolev=raf astım 10
Bicana=raf astım 10
Ventosal=raf astım 10
Erostin=raf astım 10
Erdostin=raf astım 10
Asist=raf astım 10
Bonviva=raf KLOSTEROL 1
Sempriban=raf KLOSTEROL 1
Aclabon=raf KLOSTEROL 1
Vegabon=raf KLOSTEROL 1
Fosavance=raf KLOSTEROL 1
Doxium=raf KLOSTEROL 2
Modet=raf KLOSTEROL 2
Venoruton=raf KLOSTEROL 2
Daflon=raf KLOSTEROL 2
Amoklavin=raf KLOSTEROL 3
Croxilex=raf KLOSTEROL 3
Klavunat=raf KLOSTEROL 3, 4
Klamoks=raf KLOSTEROL 3, 4
Augmentin=raf KLOSTEROL 4
Deltacortril=raf KLOSTEROL 5
Flantadin=raf KLOSTEROL 5
Kordexa=raf KLOSTEROL 5
Dekort=raf KLOSTEROL 5
Pomezon=raf KLOSTEROL 5
Prednol=raf KLOSTEROL 5
Levotiron=raf KLOSTEROL 6
Propycil=raf KLOSTEROL 6
Euthyrox=raf KLOSTEROL 7
Thyromazol=raf KLOSTEROL 7
Perizol=raf KLOSTEROL 7
Kolsin=raf KLOSTEROL 8
Colchicum=raf KLOSTEROL 8
Ürikoliz=raf KLOSTEROL 8
Ursovef=raf KLOSTEROL 8
Ursactive=raf KLOSTEROL 8
Prograf=raf KLOSTEROL 8
Plaquenil=raf KLOSTEROL 8
Motilium=raf KLOSTEROL 9
Antepsin=raf KLOSTEROL 9
Gastren=raf KLOSTEROL 9
Gaviscon=raf KLOSTEROL 9
Galviks=raf KLOSTEROL 9
Gasvin=raf KLOSTEROL 9, 10
Tribudat=raf KLOSTEROL 10
Pronat=raf KLOSTEROL 10
Sokal=raf KLOSTEROL 10
Metsil=raf KLOSTEROL 10
Rennie=raf KLOSTEROL 10
Refcon=raf KLOSTEROL 10
Oralac=raf KLOSTEROL 10
Terbin=raf merhem 1
Persmant=raf merhem 1
Psorcutan=raf merhem 1
Zalain=raf merhem 1
Dermatop=raf merhem 1
Beklazon=raf merhem 1
Duoderm=raf merhem 1
Momecon=raf merhem 1
Psovate=raf merhem 1
Dermo-rest=raf merhem 1
Nibulen=raf merhem 1, 3
Exelderm=raf merhem 1
Verrutol=raf merhem 1
Funderyl=raf merhem 1
M-furo=raf merhem 1
K-wellada=raf merhem 1
Dermifin=raf merhem 1
Butefin=raf merhem 1
Ectopix=raf merhem 1
Terbisil=raf merhem 1
Exoderil=raf merhem 1
Flurend=raf merhem 2
Kloroben=raf merhem 2
Andorex=raf merhem 2
Fardoben=raf merhem 2
Tanflex=raf merhem 2
Tantum=raf merhem 2
Majezik=raf merhem 2
Ketober=raf merhem 2
Ketoral=raf merhem 3
Konazol=raf merhem 3
Sebirox=raf merhem 3
Zetion=raf merhem 3
Vemcaine=raf merhem 3
Loprox=raf merhem 3
Siroksil=raf merhem 3
Passiflora=raf merhem 3
Betasalic=raf merhem 3
Betnovate=raf merhem 3
Opilox=raf merhem 3
Loceryl=raf merhem 3
Clovate=raf merhem 3
Dermovate=raf merhem 3
Atarax=raf merhem 4
Alores=raf merhem 4
Avil=raf merhem 4
Lordes=raf merhem 4
Miraderm=raf merhem 4
Allerset=raf merhem 4
Zyrtec=raf merhem 4
Deloday=raf merhem 4
Crestor=raf kolesterol A 1
Alipza=raf kolesterol A 1
Rosufix=raf kolesterol A 1
Caduet=raf kolesterol A 1
Lopid=raf kolesterol A 1
Ateroz=raf kolesterol A 1, 2
Colnar=raf kolesterol A 1, 2
Cholvast=raf kolesterol A 2
Ezetrol=raf kolesterol A 2
Livercol=raf kolesterol A 2
Pratin=raf kolesterol A 2
Pravachol=raf kolesterol A 2
Ultrox=raf kolesterol A 2
Colastin=raf kolesterol A 3
Ator=raf kolesterol A 3
Lipitor=raf kolesterol A 3
Fepatil=raf kolesterol A 4
Lipanthyl=raf kolesterol A 4
Lipofen=raf kolesterol A 4
Tarden=raf kolesterol A 4
Alvastin=raf kolesterol A 4
Contour=raf kolesterol A 5
Laset=raf kolesterol A 5
O-cal Plus=raf kolesterol A 5
Optima=raf kolesterol A 5, 6
Fampyra=raf kolesterol A 5
eBsensor=raf kolesterol A 6
Vivachek=raf kolesterol A 6
Accu-Chek=raf kolesterol A 6
Fora=raf kolesterol A 6
Lifechek=raf kolesterol A 6
Direct=raf kolesterol A 6
Calci-net=raf kolesterol A 7
Fix-at=raf kolesterol A 7
Rilutek=raf kolesterol A 7
Tenoviral=raf kolesterol A 7
Zentius=raf kolesterol A 7
Zeffix=raf kolesterol A 7
Oneptus=raf kolesterol A 7
Hednavir=raf kolesterol A 7
Pot-K=raf kolesterol A 7
Anti-potasyum=raf kolesterol A 8
Calcimax K=raf kolesterol A 8
Apeda=raf kolesterol A 8
Anti-fosfat=raf kolesterol A 8
Newcal=raf kolesterol A 8
Metoart=raf kolesterol A 9
Meksratu=raf kolesterol A 9
Enox=raf kolesterol A 9
Oksapar=raf kolesterol A 10
Xenetix=raf doğum 1
Gadovist=raf doğum 1
Opaxol=raf doğum 1
Clariscan=raf doğum 1
Biemexol=raf doğum 1
Gadonano=raf doğum 1
Cialis=raf doğum 2
Lex=raf doğum 2
Lifta=raf doğum 2
Silfect=raf doğum 2
Ertes=raf doğum 2
Longis=raf doğum 2
Ella=raf doğum 2
Josei=raf doğum 2
Jeligra=raf doğum 2
Vigaroo=raf doğum 2
Viamed=raf doğum 2
Vigrande=raf doğum 2
Degra=raf doğum 2
Viagra=raf doğum 2
Flynta=raf doğum 2
Orcafil=raf doğum 2
Leverette=raf doğum 3
Yasmin=raf doğum 3
Diane=raf doğum 3
Primolut=raf doğum 3
Yaz=raf doğum 3
Elleacnelle=raf doğum 3
Postpill=raf doğum 3
Drosetil=raf doğum 3
Drospera=raf doğum 3
Qlarista=raf doğum 3
Visanne=raf doğum 3
Ginera=raf doğum 3
Agnucaston=raf doğum 3
Cyclo-Progynova=raf doğum 3
İnfolic=raf doğum 4
Elenatal=raf doğum 4
Mom=raf doğum 4
Omepa=raf doğum 4
Metilfolat=raf doğum 4
Alasitol=raf doğum 4
Omepa VM=raf doğum 4
Venatura=raf doğum 4
Pregnom=raf doğum 4
Emodex=raf doğum 4
Folidoce=raf doğum 4
Xpecia=raf doğum 4
Folactive=raf doğum 4
Velbon=raf doğum 4
Folattro=raf doğum 4
Folic Iod=raf doğum 4
Folidays=raf doğum 4
Folic 1=raf doğum 4
İnofolic=raf doğum 4
Diofol=raf doğum 4
Gyno-max=raf doğum 5
Limenda L=raf doğum 5
Mixovul=raf doğum 5
Livagyn=raf doğum 5
Cleocin=raf doğum 5
Donaxyl=raf doğum 5
Miko-Penotran=raf doğum 5
Duphaston=raf doğum 5
Bioladin=raf doğum 5
Trisequens=raf doğum 5
Gyno-Lomexin=raf doğum 5
Estrofem=raf doğum 5
Zalain=raf doğum 5
Orgametril=raf doğum 5
Trivag=raf doğum 5
Neo-Penotran=raf doğum 5
Exagyn=raf doğum 5
Metiler=raf doğum 5
Gyno-Travogen=raf doğum 5
Mesigyna=raf doğum 6
Progestan=raf doğum 6
Tarlusal=raf doğum 6
Depo-Provera=raf doğum 6
Ketoral=raf doğum 6
Biteral=raf doğum 6
Kortos=raf doğum 6
Ornisid=raf doğum 6
Ainara=raf doğum 6
Klomen=raf doğum 6
Gynoflor=raf doğum 6
Procto=raf doğum 6
Proctolog=raf doğum 6
Anrecta=raf doğum 6
Procto-Glyvenol=raf doğum 6
Madopar=raf doğum 7
Qalyviz=raf doğum 7
Letu=raf doğum 7
Methotrexat=raf doğum 7
Arava=raf doğum 7
Dostinex=raf doğum 7
Ralef=raf doğum 7
Lamictal=raf doğum 7
Tamoksit=raf doğum 7
Reumil=raf doğum 7
Arimidex=raf doğum 7
Tamoxifen=raf doğum 7
Urocit-K=raf doğum 7
Transamine=raf doğum 7
İmuran=raf doğum 7
Zedprex=raf doğum 8
Trileptal=raf doğum 8
Tegretol=raf doğum 8
Risperdal=raf doğum 8
Keppra=raf doğum 8
Depakin=raf doğum 8
Convulex=raf doğum 8
Maxthio=raf doğum 9
Melox=raf doğum 9
Rif=raf doğum 9
Novalgin=raf doğum 9
Flexo=raf doğum 9
Avil=raf doğum 9
Tilcotil=raf doğum 9
Muscoril=raf doğum 9
Sustanon=raf doğum 9
Cezol=raf doğum 10
Devapen=raf doğum 10
Multisef=raf doğum 10
Dekort=raf doğum 10
Klindan=raf doğum 10
Amilozit=raf doğum 10
Citanest=raf doğum 10
Deposilin=raf doğum 10
Desefin=raf doğum 10
İespor=raf doğum 10
Kristalize=raf doğum 10
Kenacort=raf doğum 10
İesef=raf doğum 10
Sulcid=raf doğum 10
Mictonorm=raf far damla 1
Minirin=raf far damla 1
Dutapros=raf far damla 1
Xaflu=raf far damla 1
Xatral XL=raf far damla 1
Urorec=raf far damla 1
Spasmex=raf far damla 1
Kinzy=raf far damla 1
Tamprost=raf far damla 1
Betmiga=raf far damla 2
Avodart=raf far damla 2
Nexetin=raf far damla 2
Vesicare=raf far damla 2
Kentera=raf far damla 2
Emselex=raf far damla 2
Üromax=raf far damla 2
Toviaz=raf far damla 2
Toreda=raf far damla 2
Detrusitol=raf far damla 2
Eyenat=raf far damla 3
Exocin=raf far damla 3
Dryex=raf far damla 3
Dekort=raf far damla 3
Demoxif=raf far damla 3
Depores=raf far damla 3
Combigan=raf far damla 3
Zylet=raf far damla 6
Zaditen=raf far damla 6
Visine=raf far damla 6
Tears Naturale=raf far damla 6
Thealoz=raf far damla 6, 7
Tobrex=raf far damla 6
Tobrased=raf far damla 6, 7
Syzol=raf far damla 6
Simbrinza=raf far damla 6
Bausch=raf far damla 7
Virgan=raf far damla 7
Terramycin=raf far damla 7
Thiocilline=raf far damla 7
Gentamisin=raf far damla 7
Stafine=raf far damla 7
Maxidex=raf far damla 7
Lipotears=raf far damla 7
Videma=raf far damla 7
Visuxl=raf far damla 7
Swab=raf far damla 7
Otipax=raf far damla 7
Cortimycine=raf far damla 7
Ciloxan=raf far damla 7
Fusix=raf far damla 7
Fucithalmic=raf far damla 7
Fillfresh=raf far damla 8
Novaqua=raf far damla 8
Luron=raf far damla 8
Blefaritto=raf far damla 8
Refresh=raf far damla 8
Tears=raf far damla 8
Panthenol Eye=raf far damla 8
Latafree=raf far damla 8
Hyonat=raf far damla 8
Netildex=raf far damla 8
Prolutex=raf far damla 9
Celestone=raf far damla 9
Ferinject=raf far damla 9
Fostimon=raf far damla 9
Zidim=raf far damla 9
Efedrin=raf far damla 9
Citanest=raf far damla 9
Jectofer=raf far damla 9
Biteral=raf far damla 9
Proluton=raf far damla 9
Buscopan=raf far damla 9
Jetmonal=raf far damla 9
Ovitrelle=raf far damla 9
Progestan=raf far damla 9
Evin=raf far damla 9
Coplanin=raf far damla 9
Meriofert=raf far damla 10
Prednol=raf far damla 10
Linkomisin=raf far damla 10
Clopixol=raf far damla 10
Genta=raf far damla 10
Lincocin=raf far damla 10
Deksamet=raf far damla 10
Amijeksin=raf far damla 10
Redoxon=raf far damla 10
Jetokain=raf far damla 10
Evigen=raf far damla 10
Calcitron=raf far damla 10
İnfenil=raf far damla 10
Metpamid=raf far damla 10
Alatab=raf diyabet 1
Thioctacid=raf diyabet 1
Tiopati-B=raf diyabet 1
Dropia=raf diyabet 1
Glifor=raf diyabet 1, 5, 6
Glucobay=raf diyabet 2
Synjardy=raf diyabet 2
Jardiance=raf diyabet 2
Forziga=raf diyabet 3
Trajenta=raf diyabet 3
Janumet=raf diyabet 3
Galvus Met=raf diyabet 3
Januvia=raf diyabet 3
Onglyza=raf diyabet 4
Vildabet=raf diyabet 4
Vidaptin Met=raf diyabet 4
Diyatix=raf diyabet 4
Matofin=raf diyabet 4
Vildega=raf diyabet 5
Thincal=raf diyabet 5
Teglix=raf diyabet 5
Vidaptin=raf diyabet 5
İnglex=raf diyabet 5
Diaformin=raf diyabet 6
Glukofen=raf diyabet 6
Betanorm=raf diyabet 7
Glimax=raf diyabet 7
Amaryl=raf diyabet 7
Canderel=raf diyabet 7
Diamicron=raf diyabet 7
BD Micro-Fine=raf diyabet 8
Coldfine=raf diyabet 8
Fine-Ject=raf diyabet 8, 9
Goldfine=raf diyabet 8
Levopront=raf diyabet 9
Antibeksin=raf diyabet 9
Kreval=raf diyabet 10
Butirol Fort=raf diyabet 10
Notuss Fort=raf diyabet 10
Busicod=raf diyabet 10
Sinecod=raf diyabet 10
Oksabron=raf diyabet 10
Tusebron=raf diyabet 10
Perebron=raf diyabet 10
Talcid=raf mide 1
Rennie=raf mide 1
Metsil=raf mide 1
Kreon=raf mide 1
Trio=raf mide 1
Gaviscon=raf mide 1
Onzyd=raf mide 2
Zirid=raf mide 2
Dramamine=raf mide 2
Metpamid=raf mide 2, 10
Prilam DR=raf mide 2
Motilium=raf mide 2
Antiem=raf mide 2
Zofer=raf mide 2
Santis=raf mide 2
Kytril=raf mide 2
Granexa=raf mide 2
Emedur=raf mide 2
Antepsin=raf mide 2
Granitron=raf mide 2
Sandoz=raf mide 3
Panocer=raf mide 3
Pantactive=raf mide 3
Protonex=raf mide 3
Pantpas=raf mide 3
Panthec=raf mide 3
Lansor=raf mide 4
Pandev=raf mide 4
Degastrol=raf mide 4
Lansoter=raf mide
`;